lc_agenda:
    resource: "@LcAgendaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"